<?php
/**
 * Created by PhpStorm.
 * User: Viktoriya
 * Date: 21.12.2017
 * Time: 18:24
 */

namespace app\models;
use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    public static function tableName()
    {
       // return parent::tableName(); // TODO: Change the autogenerated stub
        return 'category';
    }
     public function getProducts() {
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
     }
}